
class PyCubeCAN:
    def startPrintLog(self, prefix: bytes, path: bytes, level: int):
        ...

    def version(self):
        ...

    def setAuth(self, username: bytes, password: bytes):
        ...

    def start(self):
        ...

    def stop(self):
        ...

    def sendMessage(self, command: int, data: bytes, toAppType: int, 
            toSessionId: int, msTimeout: int) -> bytes:
        ...

    def postMessage(self, command: int, data: bytes, toAppType: int, 
            toSessionId: int) -> bytes:
        ...

    def pushMessage(self, command: int, data: bytes):
        ...

    def replyMessage(self, header: bytes, rspCommand: int, data: bytes, bodyType: int):
        ...

    def setRequestHandler(self, cb: Callable[[int,bytes,bytes],None]):
        ...

    def setResponseHandler(self, cb: Callable[[int,bytes,bytes,bytes],None]):
        ...

    def setPublishHandler(self, cmds, cb: Callable[[int,bytes,bytes],None]):
        ...

    def setStatusChangedHandler(self, cb: Callable[[int],None]):
        ...

    def myAppType(self):
        ...

    def mySessionId(self):
        ...

    def startCenterController(self):
        ...
    
    def getAppInfo(self, sessionId: int):
        ...

    def getSessionId(self, appType: int):
        ...

    def getMyBind(self, appType: int):
        ...

    def getByBind(self, appType: int):
        ...

    def getDebugLog(self):
        ...

    def registerApp(self, resType: int):
        ...

    def unregisterApp(self):
        ...
    
    def mallocApp(self, dstAppType: int, resType: int):
        ...

    def freeApp(self, dstAppType: int, dstSessionId: int, resType: int):
        ...
